version: '3.3'
services:
  
  flask:
    build: ./vuln-screenshot
    container_name: vuln-screenshot
    restart: always
    environment:
      - APP_NAME=VulnerableScreenshotService
    volumes:
      - display-image:/app
    ports:
      - "8888:8888"

  nginx:
     build: ./nginx
     container_name: nginx
     restart: always
     depends_on:
       - flask
     volumes:
       - display-image:/usr/share/nginx/app
     ports:
       - "5000:80"

volumes:
  display-image:
